---
title: "p8105_hw5_bs3142"
author: "Bingyu Sun"
date: "11/3/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

library(tidyverse)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Problem 1

### Data import

```{r}
read_study = function(flnm) {
  read_csv(flnm) %>%
    mutate(filename = flnm)
}

study_data = 
  list.files(path = "./data",
             pattern = "*.csv",
             full.names = TRUE) %>%
  map_df(~read_study(.x))
```

### Data tidying

```{r}
tidy_study =
  study_data %>%
  mutate(filename = str_replace_all(filename, c("^./data/" = "", ".csv$" = ""))) %>%
  separate(filename, into = c("treatment", "id"), sep = "_") %>%
  mutate(treatment = str_replace_all(treatment, c("con" = "control", "exp" = "experiment"))) %>%
  gather(key = week, value = value, week_1:week_8) %>%
  mutate(week = str_replace(week, "^week_", ""))
```

### Spaghetti plot

```{r}
tidy_study %>%
  mutate(week = as.numeric(week)) %>%
  group_by(treatment, id) %>% 
  ggplot(aes(x = week, y = value, color = id)) +
  geom_line() +
  facet_grid(~treatment) +
  labs(
    title = "Observations of Each Subject Over Time by Treatment"
  ) +
  viridis::scale_color_viridis(
    name = "Subject ID",
    discrete = TRUE
  )
```

